[project]
name = "caad-erp"
version = "0.1.0"
description = "Excel-backed inventory and sales tracker for student lounges"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pytest>=8.4.2",
]
